name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: |
    or(
      eq(variables['Build.Reason'], 'Manual'),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['Build.Reason'], 'IndividualCI')
    )
  pool:
    vmImage: ubuntu-latest

  variables:
    - group: Azure-Static-Web-Apps-gray-moss-0038e2e0f-variable-group

  steps:
    - checkout: self
      submodules: true

    - task: UseNode@1
      inputs:
        version: '18.x'
      displayName: 'Use Node.js 18'

    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_MOSS_0038E2E0F)
        app_location: "/"
        api_location: ""
        output_location: ".next"