name: Azure Static Web Apps CI/CD
trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: |
    or(
      eq(variables['Build.Reason'], 'Manual'),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['Build.Reason'], 'IndividualCI')
    )
  pool:
    vmImage: ubuntu-latest

  variables:
    - group: azure-static-web-dev

  steps:
    - checkout: self
      submodules: true

    - task: UseNode@1
      inputs:
        version: '18.x'
      displayName: 'Use Node.js 18'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/'
        app_build_command: 'npm run build'
        output_location: '.next'
        verbose: true
        build_timeout_in_minutes: 15
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_MOSS_0038E2E0F)'
        production_branch: 'dev'
        skip_api_build: true
      env:
        NEXT_PUBLIC_API_URL: $(NEXT_PUBLIC_API_URL)
        NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN: $(NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN)
        NEXT_PUBLIC_B2C_BASE_AUTHORITY: $(NEXT_PUBLIC_B2C_BASE_AUTHORITY)
        NEXT_PUBLIC_B2C_CLIENT_ID: $(NEXT_PUBLIC_B2C_CLIENT_ID)
        NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI: $(NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI)
        NEXT_PUBLIC_B2C_REDIRECT_URI: $(NEXT_PUBLIC_B2C_REDIRECT_URI)
        NEXT_PUBLIC_B2C_SCOPE_BASE: $(NEXT_PUBLIC_B2C_SCOPE_BASE)
