name: NextJS Static Web App CI/CD (with local build)

trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: artifactName
    value: 'staticwebapp_$(Build.BuildId)'
  - name: baseVersion
    value: '1.0.0'
  - name: buildVersion
    value: '$(baseVersion)-build-$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build Next.js Locally'
  jobs:
    - job: BuildJob
      displayName: 'Build and Package'
      steps:
        - checkout: self
          submodules: true

        - task: UseNode@1
          displayName: 'Use Node.js 18'
          inputs:
            version: '18.x'

        - script: |
            npm install
          displayName: 'Install dependencies'

        - script: |
            npm run build
          displayName: 'Run Next.js Build'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Build Output (.next)'
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)'
            artifact: $(artifactName)

- stage: DeployDev
  displayName: 'Deploy to Static Web App (Dev)'
  dependsOn: Build
  variables:
    - group: Dev-Variables
  jobs:
    - deployment: DeployDevJob
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: $(artifactName)

              - task: AzureStaticWebApp@0
                displayName: 'Deploy to Static Web App - Dev'
                inputs:
                  app_location: '/'                  # Use root of app
                  output_location: '.next'           # Use local build output
                  skip_app_build: true               # ✅ We already built!
                  skip_api_build: true
                  azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APP_FRONTEND)'
                  production_branch: 'main'
                env:
                  NEXT_PUBLIC_API_URL: $(NEXT_PUBLIC_API_URL)
                  NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN: $(NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN)
                  NEXT_PUBLIC_B2C_BASE_AUTHORITY: $(NEXT_PUBLIC_B2C_BASE_AUTHORITY)
                  NEXT_PUBLIC_B2C_CLIENT_ID: $(NEXT_PUBLIC_B2C_CLIENT_ID)
                  NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI: $(NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI)
                  NEXT_PUBLIC_B2C_REDIRECT_URI: $(NEXT_PUBLIC_B2C_REDIRECT_URI)
                  NEXT_PUBLIC_B2C_SCOPE_BASE: $(NEXT_PUBLIC_B2C_SCOPE_BASE)

              - script: |
                  curl -H "Content-Type: application/json" \
                       -d "{\"text\":\"✅ Dev Deployment Complete\\nBuild ID: $(Build.BuildId)\\nVersion: $(buildVersion)\\nCommit: $(Build.SourceVersion)\"}" \
                       "https://levelupyourdata.webhook.office.com/webhookb2/..."
                displayName: 'Notify Teams - Dev'

- stage: DeployProd
  displayName: 'Deploy to Static Web App (Prod)'
  dependsOn: DeployDev
  condition: succeeded()
  variables:
    - group: Prd-Variables
  jobs:
    - deployment: DeployProdJob
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: $(artifactName)

              - task: AzureStaticWebApp@0
                displayName: 'Deploy to Static Web App - Prod'
                inputs:
                  app_location: '/'
                  output_location: '.next'
                  skip_app_build: true
                  skip_api_build: true
                  azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APP_FRONTEND)'
                  production_branch: 'main'
                env:
                  NEXT_PUBLIC_API_URL: $(NEXT_PUBLIC_API_URL)
                  NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN: $(NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN)
                  NEXT_PUBLIC_B2C_BASE_AUTHORITY: $(NEXT_PUBLIC_B2C_BASE_AUTHORITY)
                  NEXT_PUBLIC_B2C_CLIENT_ID: $(NEXT_PUBLIC_B2C_CLIENT_ID)
                  NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI: $(NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI)
                  NEXT_PUBLIC_B2C_REDIRECT_URI: $(NEXT_PUBLIC_B2C_REDIRECT_URI)
                  NEXT_PUBLIC_B2C_SCOPE_BASE: $(NEXT_PUBLIC_B2C_SCOPE_BASE)

              - script: |
                  curl -H "Content-Type: application/json" \
                       -d "{\"text\":\"🚀 Prod Deployment Complete\\nBuild ID: $(Build.BuildId)\\nVersion: $(buildVersion)\\nCommit: $(Build.SourceVersion)\"}" \
                       "https://levelupyourdata.webhook.office.com/webhookb2/..."
                displayName: 'Notify Teams - Prod'
