name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - dev

pr:
  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

variables:
  - name: baseVersion
    value: '1.0.0'
  - name: buildVersion
    value: '$(baseVersion)-build-$(Build.BuildId)'

stages:
- stage: DeployDev
  displayName: 'Deploy to Static Web App (Dev)'
  variables:
    - group: Dev-Variables
  jobs:
    - job: DeployDevJob
      displayName: 'Build and Deploy to Dev'
      steps:
        - checkout: self
          submodules: true

        - task: UseNode@1
          displayName: 'Use Node.js 18'
          inputs:
            versionSpec: '18.x'

        - task: AzureStaticWebApp@0
          displayName: 'Azure Static Web App Deploy - Dev'
          inputs:
            app_location: '/'                   # ✅ your repo root
            app_build_command: 'npm run build'   # ✅ build handled inside Azure
            output_location: '.next'             # ✅ standard next.js output
            skip_api_build: true
            azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APP_FRONTEND)'
            production_branch: 'main'
          env:
            NEXT_PUBLIC_API_URL: $(NEXT_PUBLIC_API_URL)
            NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN: $(NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN)
            NEXT_PUBLIC_B2C_BASE_AUTHORITY: $(NEXT_PUBLIC_B2C_BASE_AUTHORITY)
            NEXT_PUBLIC_B2C_CLIENT_ID: $(NEXT_PUBLIC_B2C_CLIENT_ID)
            NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI: $(NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI)
            NEXT_PUBLIC_B2C_REDIRECT_URI: $(NEXT_PUBLIC_B2C_REDIRECT_URI)
            NEXT_PUBLIC_B2C_SCOPE_BASE: $(NEXT_PUBLIC_B2C_SCOPE_BASE)

        - script: |
            curl -H "Content-Type: application/json" \
                 -d "{\"text\":\"✅ Dev Deployment Complete!\\nBuild ID: $(Build.BuildId)\\nVersion: $(buildVersion)\\nCommit: $(Build.SourceVersion)\"}" \
                 "$(TEAMS_WEBHOOK)"
          displayName: 'Notify Teams - Dev'

- stage: DeployProd
  displayName: 'Deploy to Static Web App (Prod)'
  dependsOn: DeployDev
  condition: succeeded()
  variables:
    - group: Prd-Variables
  jobs:
    - deployment: DeployProdJob
      environment: 'production' # ✅ Make sure environment 'production' in DevOps requires approval
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: true

              - task: UseNode@1
                displayName: 'Use Node.js 18'
                inputs:
                  versionSpec: '18.x'
                  
              - script: |
                  echo "🔍 Printing key deployment variables:"
                  echo "AZURE_STATIC_WEB_APP_FRONTEND = ${AZURE_STATIC_WEB_APP_FRONTEND:-(not set)}"
                  echo "NEXT_PUBLIC_API_URL = ${NEXT_PUBLIC_API_URL:-(not set)}"
                  echo "NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN = ${NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN:-(not set)}"
                  echo "NEXT_PUBLIC_B2C_BASE_AUTHORITY = ${NEXT_PUBLIC_B2C_BASE_AUTHORITY:-(not set)}"
                  echo "NEXT_PUBLIC_B2C_CLIENT_ID = ${NEXT_PUBLIC_B2C_CLIENT_ID:-(not set)}"
                  echo "NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI = ${NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI:-(not set)}"
                  echo "NEXT_PUBLIC_B2C_REDIRECT_URI = ${NEXT_PUBLIC_B2C_REDIRECT_URI:-(not set)}"
                  echo "NEXT_PUBLIC_B2C_SCOPE_BASE = ${NEXT_PUBLIC_B2C_SCOPE_BASE:-(not set)}"
                displayName: '🔍 Debug - Print Variable Group Values'
              - task: AzureStaticWebApp@0
                displayName: 'Azure Static Web App Deploy - Prod'
                inputs:
                  app_location: '/'
                  app_build_command: 'npm run build'
                  output_location: '.next'
                  skip_api_build: true
                  azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APP_FRONTEND)'
                  production_branch: 'dev'
                env:
                  NEXT_PUBLIC_API_URL: $(NEXT_PUBLIC_API_URL)
                  NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN: $(NEXT_PUBLIC_B2C_AUTHORITY_DOMAIN)
                  NEXT_PUBLIC_B2C_BASE_AUTHORITY: $(NEXT_PUBLIC_B2C_BASE_AUTHORITY)
                  NEXT_PUBLIC_B2C_CLIENT_ID: $(NEXT_PUBLIC_B2C_CLIENT_ID)
                  NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI: $(NEXT_PUBLIC_B2C_LOGOUT_REDIRECT_URI)
                  NEXT_PUBLIC_B2C_REDIRECT_URI: $(NEXT_PUBLIC_B2C_REDIRECT_URI)
                  NEXT_PUBLIC_B2C_SCOPE_BASE: $(NEXT_PUBLIC_B2C_SCOPE_BASE)

              - script: |
                  curl -H "Content-Type: application/json" \
                       -d "{\"text\":\"🚀 Prod Deployment Complete!\\nBuild ID: $(Build.BuildId)\\nVersion: $(buildVersion)\\nCommit: $(Build.SourceVersion)\"}" \
                       "$(TEAMS_WEBHOOK)"
                displayName: 'Notify Teams - Prod'
